### ISSUE TITLE
discord commands not working

### ISSUE THREAD

**Issue by JavaDotExE** [noelvissers/djs-site-watcher#14]
I already started the bot, gave it admin perms, and set up a dedicated channel, but the discord commands aren't working. The bot's running perfectly in cmd and is online but it doesn't respond

**Comment by noelvissers** [comment]
Hi, discord changed the way bots work. This means the commands dont work anymore unfortunately. I dont have time to fix this either, so for now it might be better to look for something else or create a fork and update the bot yourself.
