### ISSUE TITLE
Error: TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by Stemp123** [noelvissers/djs-site-watcher#5]
I get this error when (I think) it tries to send a message when the site updates since I don't get any update notifications. But all other commands seem to work. 

Example:
```
[Sten#6293]: !update
[ 'update' ]
Error: TypeError: Cannot read property 'send' of undefined
```

**Comment by noelvissers** [comment]
Make sure the bot has the right permissions in the channel youre trying to use the command in.
